# config.yaml

save_data: data_vs6_2/vocab
## Where the vocab(s) will be written
src_vocab: data_vs6_2/train-src.vocab
tgt_vocab: data_vs6_2/train-tgt.vocab

# Corpus opts:
data:
    gold_silver:
        path_src: data_vs6_2/train-src.txt
        path_tgt: data_vs6_2/train-tgt.txt
        weight: 1
    valid:
        path_src: data/dev/dev-src.txt
        path_tgt: data/dev/dev-tgt.txt

# General opts
save_model: models/exp2
save_checkpoint_steps: 10000
valid_steps: 10000 
train_steps: 288413 # around 30 epochs 
# len(train_data)/batch_size = 1,230,565/32

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "sents"
batch_size: 8
valid_batch_size: 4
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 0.2 # Originally 2 
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
