# config.yaml

save_data: data/vocab 
## Where the vocab(s) will be written
src_vocab: data/vocab.src
tgt_vocab: data/vocab.tgt

# Corpus opts:
data:
    gold_silver:
        path_src: data/train/train-src.txt
        path_tgt: data/train/train-tgt.txt
        weight: 1
    valid:
        path_src: data/dev/dev-src.txt
        path_tgt: data/dev/dev-tgt.txt

# General opts
save_model: models/exp1
save_checkpoint_steps: 5000
valid_steps: 5000
train_steps: 200000

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "sents"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
